[APDV-110] added JWT to all requests
pploszczyca/Air-Pollution-Data-Visualizer pull request #45
Opened 2022-08-22 22:31 UTC by kkoz3434

2022-08-23 16:25 UTC, pploszczyca requested changes

2022-08-23 16:25 UTC, pploszczyca commented on frontend/lib/Repository/UserRepository/UserGateway.dart
> +      return AuthResponse(success: true, tokens: user.tokenResponse);
Ta funkcja powinna wyglądać tak. Jeżeli jesteśmy na ekranie logowania/rejestrowania to ZAWSZE chcemy zapisać nowy token. Jeżeli tego nie naprawimy to apka nie będzie działać :crying_cat_face: 
```dart
Future<AuthResponse> authenticateUser(AuthenticateForm form) async {
      final AuthResponse response = await authGetaway.authenticateUser(form);
      user = response.success ? User(response.tokens!) : User.empty();
      await secureStorage.write(
          key: accessKey, value: response.tokens!.accessToken);
      await secureStorage.write(
          key: refreshKey, value: response.tokens!.refreshToken);
      return response;
}
```

2022-08-23 16:25 UTC, pploszczyca commented on frontend/lib/Repository/AdminRepository/GroupsRepository.dart
>      _client.options.headers["Authorization"] = "Bearer $token";
Tutaj prawidłowy token nie jest dodawany, tylko mockowy

2022-08-23 16:25 UTC, pploszczyca commented on frontend/lib/Repository/EndpointRepository/EndpointGateway.dart
> +    endpointCache.saveEndpointSummary(summary);
Czemu tutaj dokonałeś zmian? Jak dla mnie było dobrze wcześniej, bo dostajemy Future z repozytorium, na boku zapisujemy i lecimy dalej z `summary`. Natomiast tutaj czekamy, aż pobierzemy z repozytorium i dopiero wtedy idziemy dalej

2022-08-23 16:25 UTC, pploszczyca commented on frontend/lib/Repository/EndpointRepository/EndpointGateway.dart
> +            id, limit, offset, userGateway.user.tokenResponse.accessToken);
Trochę nie podoba mi się wywołanie `userGateway.user.tokenResponse.accessToken`. Najlepiej by było, jakbyśmy mieli jakiegoś `Provider'a`, który dostarcza nam ten `accessToken`. Może to być klasa z metodą `getAccessToken`, a w środku mamy wywołanie `secureStorage.read(key: accessKey)`. Taką klasę można potem spokojnie wstrzykiwać w różnych `gateway'ach`

2022-08-31 17:17 UTC, pploszczyca approved these changes

2022-08-31 17:17 UTC, pploszczyca commented on frontend/lib/Repository/UserRepository/UserGateway.dart
>        return AuthResponse(success: true, tokens: user.tokenResponse);
Czy tak nie będzie prościej? :thinking: 
```suggestion
      return AuthResponse(
          success: true, 
          tokens: AuthTokenResponse(accessToken: access, refreshToken: refresh)
       );
```

2022-08-31 17:17 UTC, pploszczyca commented on frontend/lib/Repository/AdminRepository/GroupsRepository.dart
> +    if (authResponse.success) {
Czy jeżeli pobranie `authResponse` się nie powiedzie, to czy nie powinniśmy przejść do ekranu logowania? :thinking: Myślę, że to będzie do zrobienia w tasku z flow logowania [APDV-124](https://brzezins.atlassian.net/browse/APDV-124)

2022-08-31 17:17 UTC, pploszczyca commented on frontend/lib/Repository/AdminRepository/GroupsRepository.dart
> +                .toList();
:thinking: 
```suggestion
            List<GroupSummary> groupSummaryList =  backendResponse.data
                .map<GroupSummary>((e) =>
                    GroupSummary.fromJson(e)) // do not refactor! UFO MAGIC!
                .toList();
```

2022-08-31 17:22 UTC, kkoz3434 commented on frontend/lib/Repository/AdminRepository/GroupsRepository.dart
> +                .toList();
przyczajony tygrys, ukryty smok

2022-08-31 17:42 UTC, merged