[APDV-87] profile view and layout refactor
pploszczyca/Air-Pollution-Data-Visualizer pull request #61
Opened 2022-09-08 20:10 UTC by kkoz3434

Profil użytownika + mała zmiana widoków. 
Pozwoliłem sobie na małą samowolkę, oceńcie efekty :lenny:

2022-09-09 18:49 UTC, pploszczyca reviewed
Podoba mi się nowe tło w tle, oraz panel użytkownika też spoko wygląda :sunglasses: 

Jednak trzeba niestety parę glichy ponaprawiać :face_with_head_bandage: 

1. Na ekranie Profilu Użytkownika guzik wyloguj coś się psuje
![Screenshot_20220909_200106](https://user-images.githubusercontent.com/37903018/189422053-392e56be-3f6c-48cf-bd88-18059ba07dba.png)

2. Przy Compare Endpoints przy widget'ach widać białą ramkę. Może da się ustawić przeźroczysty background?
![Screenshot_20220909_200342](https://user-images.githubusercontent.com/37903018/189422548-c5bf9342-8acb-4ece-af42-99c7a76bc2e2.png)

3. Ciut mniejszy marginem górny bym ustawił, dla tab'a z temperaturą, ciśnieniem itd.
![Screenshot_20220909_200235](https://user-images.githubusercontent.com/37903018/189422817-ab9886d6-8805-43b7-ac70-575460baac0b.png)

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Routing/profile_navigator.dart
>        );
Nie można tak:
```dart
onGenerateRoute: (settings) => 
    MaterialPageRoute<dynamic>(builder: (context) => ProfileView(widget.userGateway));
```

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Views/compare_endpoints_view.dart
> +              ),
Imo całe  `const BoxDecoration` wrzuciłbym do jakiegoś pliku `widgets_decorations`, bo to tło zapewne będzie się powtarzało w wielu miejscach

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Views/profile_view.dart
> +                  buildLogoutButton(context)
Czy zamiast opierać się na `specer'ach` nie lepiej ustawić widżetom marginesy?

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Views/profile_view.dart
> +            ),
Mam wrażenie, że ten kawałek kodu widzę już w której PR'ce. Może dało by się go wrzucić do jakiś `common_styles`?

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Views/profile_view.dart
> +  SizedBox buildLogoutButton(BuildContext context) => SizedBox(
Kolejność funkcji się nie zgadza. Pisząc kod trzeba się starać, żeby można go było czytać od góry do dołu. W tym przypadku najpierw powinna być funkcja `buildAvatarContainer`, po niej `buildRoleContainer`, a dopiero na samym końcu `buildLogoutButton`

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Views/profile_view.dart
> +            bullet + " " + e.toString().split('.').last,
```suggestion
      .map(
        (role) => Center(
          child: Text(
            bullet + " " + role.toString().split('.').last,
```

2022-09-09 18:49 UTC, pploszczyca commented on frontend/lib/Widgets/common_widgets.dart
> +PreferredSize buildFancyAppBar(String title) => PreferredSize(
`fancyAppBar` XD

2022-09-11 12:45 UTC, zbrze commented
![image](https://user-images.githubusercontent.com/58784685/189528149-3f6987bf-15d3-43cf-b7cc-0ff803356aa2.png)
 
Ogolnie to proponuje zmienic ciut ux na taki - brak dwukropków (chłop z ux mowił że do wywalenia), zmienilam ciut wyglad awatara i button nie jest outlined - skoro nie ma solid tła to imo nie powinno się robić ramki, zfixowałam kolor tekstu i ikonki, żeby po najechaniu sie kolorowały na biało, całość kodu bd w zaproponuj zmiany

2022-09-11 12:56 UTC, zbrze requested changes

2022-09-11 12:56 UTC, zbrze commented on frontend/lib/Views/profile_view.dart
> +            backgroundColor: MaterialStateProperty.resolveWith<Color>(
Dorzuć ten fragment plox, z ustawianiem foreground color, bo inaczej, jak sie hoveruje na tym guziku to tlo sie zminenia na różowe, a tekst zostaje różowy i nic nie widać
```dart
  foregroundColor: MaterialStateProperty.resolveWith<Color>(
              (Set<MaterialState> states) =>
                  states.contains(MaterialState.hovered)
                      ? Colors.white
                      : Colors.red,
            ),
```

2022-09-11 12:56 UTC, zbrze commented on frontend/lib/Views/profile_view.dart
> +                  color: Colors.pink,
nie ustawiaj tego jako children, tylko jako label i icon i bedzie zmieniac kolor i samo się dobrze ułoży, nie trzeba rowa wtedy

2022-09-11 12:56 UTC, zbrze commented on frontend/lib/Views/endpoint_view.dart
> +                    Color.fromRGBO(14, 14, 82, 0.9)
te rgbo pojawiają się w kodzie 5 razy, proponuję przypisać do stałej

2022-09-11 12:56 UTC, zbrze commented on frontend/lib/Views/profile_view.dart
> +                  buildLogoutButton(context)
+1

2022-09-11 12:56 UTC, zbrze commented on frontend/lib/Views/profile_view.dart
> +  SizedBox buildLogoutButton(BuildContext context) => SizedBox(
czm nie prywatne metody?

2022-09-11 12:56 UTC, zbrze commented on frontend/lib/Views/profile_view.dart
> +import 'package:adpv_frontend/Repository/UserRepository/user_gateway.dart';
```suggestion
import 'package:adpv_frontend/Repository/UserRepository/user_gateway.dart';
import 'package:adpv_frontend/Views/Logging/login_view.dart';
import 'package:adpv_frontend/Widgets/common_widgets.dart';
import 'package:flutter/material.dart';

class ProfileView extends StatefulWidget {
  final UserGateway userGateway;

  const ProfileView(this.userGateway, {Key? key}) : super(key: key);

  @override
  State<ProfileView> createState() => _ProfileViewState();
}

String bullet = "\u2022 ";

class _ProfileViewState extends State<ProfileView> {

  @override
  Widget build(BuildContext context) => Scaffold(
        backgroundColor: const Color.fromARGB(255, 127, 166, 168),
        appBar: buildFancyAppBar("Your Profile"),
        body: Container(
          height: MediaQuery.of(context).size.height,
          width: double.infinity,
          alignment: Alignment.topCenter,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topRight,
              end: Alignment.bottomLeft,
              colors: [
                Color.fromRGBO(21, 184, 194, 1),
                Color.fromRGBO(14, 14, 82, 0.9)
              ],
            ),
          ),
          child: SingleChildScrollView(
            child: SizedBox(
              height: MediaQuery.of(context).size.height * 0.7,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  _buildAvatarContainer(),
                  _buildRoleContainer(),
                  _buildLogoutButton(context)
                ],
              ),
            ),
          ),
        ),
      );

  Container _buildAvatarContainer() => Container(
        height: MediaQuery.of(context).size.height * 0.2,
        width: MediaQuery.of(context).size.width * 0.9,
        decoration: const BoxDecoration(
          borderRadius: BorderRadius.all(Radius.circular(5)),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            _buildRoundAvatar(),
            Center(
              child: Text(
                widget.userGateway.user.email,
                style: const TextStyle(
                  fontStyle: FontStyle.normal,
                  color: Colors.white,
                  fontSize: 24,
                ),
              ),
            ),
          ],
        ),
      );

  SizedBox _buildRoundAvatar() => SizedBox(
        height: 100,
        width: 100,
        child: DecoratedBox(
          decoration: BoxDecoration(
            color: Colors.pink,
            border: Border.all(
              color: Colors.pink,
            ),
            borderRadius: const BorderRadius.all(Radius.circular(90)),
          ),
          child: Center(
            child: Text(
              widget.userGateway.user.email[0].toUpperCase(),
              style: const TextStyle(
                fontStyle: FontStyle.normal,
                color: Colors.white,
                fontSize: 56,
              ),
            ),
          ),
        ),
      );

  Container _buildRoleContainer() => Container(
        padding: const EdgeInsets.symmetric(vertical: 20, horizontal: 15),
        height: MediaQuery.of(context).size.height *
                0.09 *
                widget.userGateway.user.userRoles.length +
            30,
        width: MediaQuery.of(context).size.width * 0.9,
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.all(
            Radius.circular(5),
          ),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              "Your roles",
              style: TextStyle(
                fontFamily: 'SofiaSans',
                color: Colors.pink,
                fontSize: 32,
              ),
            ),
            const Divider(
              height: 20,
              thickness: 2,
              indent: 0,
              endIndent: 0,
              color: Colors.grey,
            ),
            Center(
              child: Column(
                children: listRoles(),
              ),
            )
          ],
        ),
      );

  List<Widget> listRoles() => widget.userGateway.user.userRoles
      .map(
        (e) => Container(
          padding: const EdgeInsets.symmetric(vertical: 7, horizontal: 10),
          alignment: Alignment.centerLeft,
          child: Text(
            bullet + " " + e.toString().split('.').last,
            style: const TextStyle(
              fontFamily: 'SofiaSans',
              color: Color.fromARGB(255, 100, 100, 100),
              fontSize: 24,
            ),
          ),
        ),
      )
      .toList();

  SizedBox _buildLogoutButton(BuildContext context) => SizedBox(
        width: MediaQuery.of(context).size.width * 0.5,
        child: TextButton.icon(
          label: const Text(
            "LOG OUT",
            style: TextStyle(
              fontFamily: 'SofiaSans',
              fontSize: 26,
            ),
          ),
          icon: const Icon(
            Icons.logout,
            size: 32,
          ),
          style: ButtonStyle(
            padding: MaterialStateProperty.all(const EdgeInsets.all(20)),
            backgroundColor: MaterialStateProperty.resolveWith<Color>(
              (Set<MaterialState> states) =>
                  states.contains(MaterialState.hovered)
                      ? Colors.pink
                      : Colors.white,
            ),
            foregroundColor: MaterialStateProperty.resolveWith<Color>(
              (Set<MaterialState> states) =>
                  states.contains(MaterialState.hovered)
                      ? Colors.white
                      : Colors.pink,
            ),
            shape: MaterialStateProperty.all(
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
            ),
          ),
          onPressed: () {
            widget.userGateway.resetMemoryToken();
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(
                builder: (BuildContext context) =>
                    LoginView(userGateway: widget.userGateway),
              ),
            );
          },
        ),
      );
}

```

2022-09-11 13:16 UTC, kkoz3434 commented on frontend/lib/Views/profile_view.dart
> +                  buildLogoutButton(context)
jak chcecie

2022-09-11 13:17 UTC, kkoz3434 commented on frontend/lib/Views/profile_view.dart
> +  SizedBox buildLogoutButton(BuildContext context) => SizedBox(
ctrl+alt+m, zaraz poprawię

2022-09-11 14:30 UTC, pploszczyca reviewed
Nadal widać białe paski przy wyborze endpoint'ów:
![image](https://user-images.githubusercontent.com/37903018/189532960-8083005c-984f-464c-8d85-1d536ee711b5.png)

Tutaj też coś się psuje:
![image](https://user-images.githubusercontent.com/37903018/189533006-d75b83d1-01ff-4f4b-b8eb-967ab420ba54.png)

2022-09-11 15:50 UTC, pploszczyca approved these changes
Compare Endpoints wydaje się nie do naprawienia niestety :crying_cat_face:

2022-09-12 18:27 UTC, zbrze approved these changes

2022-09-13 15:12 UTC, merged